MF=     Makefile.gcc
 
CC=     g++
 
CFLAGS= -D_USE_64 -msse3 -O3 -fomit-frame-pointer -funroll-loops 
 
LFLAGS= -std=c++17 -O3 -DNDEBUG -I ./

EXE=    random
 
SRC=    random.cc
 
HD=     Makefile.gcc
 
# 
# No need to edit below this line 
# 
 
.SUFFIXES: 
.SUFFIXES: .cc .o 
 
OBJ=    $(SRC:.cc=.o) 
 
.cc.o: 
	$(CC) $(CFLAGS)-c $(LFLAGS) $< 
 
all:    $(EXE) 
 
$(EXE): $(OBJ) 
	$(CC) $(CFLAGS) -o $@ $(OBJ) $(LFLAGS) 
 
$(OBJ): $(MF) $(HD) 
 
clean: 
	rm -f $(OBJ) $(EXE) *~

